name: WPCS checker
on: push
jobs:
  linter_name:
    name: runner / phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shalior/action-phpcs-wordpress@v1.6.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          phpcs_standard: MySource
          use_default_configuration_file: true