name: WPCS checker
on: push
jobs:
  linter_name:
    name: runner / phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shalior/action-phpcs-wordpress@master
        with:
          github_token: ${{ secrets.github_token }}
          use_default_configuration_file: true
          phpcs_args: '-n' # ignore warnings